version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - muleyuck
    cooldown:
      default-days: 2
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: saturday
      timezone: Asia/Tokyo
    commit-message:
      prefix: "chore"
      include: "scope"
