version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - muleyuck
    cooldown:
      semver-patch-days: 2
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: saturday
      timezone: Asia/Tokyo
    commit-message:
      prefix: "chore"
      include: "scope"
