name: unit-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - run: luacheck lua/ plugin/
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ plugin/
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7
        with:
          neovim: true
          version: stable
      - name: Run tests
        run: make test
